version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
        environment:
          FLASK_APP: app.py
          FLASK_ENV: testing
          PGHOST: 127.0.0.1
          PGUSER: root
      - image: circleci/postgres:10.8-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: osprey_test_db
    steps:
      - checkout
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
      - run:
          command: pipenv run nosetests --with-coverage --cover-package=routes
      - run:
          command: pipenv run codecov
