"""empty message

Revision ID: 0b166aa69d96
Revises: b229ec19dec9
Create Date: 2022-09-05 12:24:13.069106

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0b166aa69d96'
down_revision = 'b229ec19dec9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cluster_logs', sa.Column('cluster_i', sa.String(length=256), nullable=True))
    op.drop_column('cluster_logs', 'cluster_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cluster_logs', sa.Column('cluster_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.drop_column('cluster_logs', 'cluster_i')
    # ### end Alembic commands ###
