"""empty message

Revision ID: 371b602785d5
Revises: 8ecac871d2d9
Create Date: 2022-02-23 12:40:44.395164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '371b602785d5'
down_revision = '8ecac871d2d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clusters', sa.Column('liqo_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clusters', 'liqo_name')
    # ### end Alembic commands ###
