"""empty message

Revision ID: 8ecac871d2d9
Revises: 6fa9a7629442
Create Date: 2022-02-02 00:25:28.704820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ecac871d2d9'
down_revision = '6fa9a7629442'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('is_multicluster', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'is_multicluster')
    # ### end Alembic commands ###
