"""empty message

Revision ID: edc3ea775e68
Revises: 6e60fbbe5858
Create Date: 2022-09-05 10:29:09.398376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edc3ea775e68'
down_revision = '6e60fbbe5858'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cluster_logs', sa.Column('date_created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cluster_logs', 'date_created')
    # ### end Alembic commands ###
