"""empty message

Revision ID: ef3a48022046
Revises: 0b166aa69d96
Create Date: 2022-09-05 12:25:06.521003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef3a48022046'
down_revision = '0b166aa69d96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cluster_logs', sa.Column('cluster_id', sa.String(length=256), nullable=True))
    op.drop_column('cluster_logs', 'cluster_i')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cluster_logs', sa.Column('cluster_i', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_column('cluster_logs', 'cluster_id')
    # ### end Alembic commands ###
